logging:
  level:
    liquibase: INFO

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/thesis-track}
    username: ${SPRING_DATASOURCE_USERNAME:thesis-track-postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:thesis-track-postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${DEBUG_MODE:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: ${DEBUG_MODE:false}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:thesis-track-app}
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/thesis-track}
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8081/realms/thesis-track/protocol/openid-connect/certs}
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/thesis-track}
  mail:
    host: ${POSTFIX_HOST:localhost}
    port: ${POSTFIX_HOST:25}
    username: ${POSTFIX_USERNAME:}
    password: ${POSTFIX_PASSWORD:}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          starttls:
            enable: true

jwt:
  auth:
    converter:
      resource-id: ${KEYCLOAK_CLIENT_ID:thesis-track-app}
      principal-attribute: ${UNIVERSITY_ID_JWT_ATTRIBUTE:preferred_username}

thesis-track:
  client:
    host: ${CLIENT_HOST:localhost}
  mail:
    enabled: ${MAIL_ENABLED:false}
    sender: ${MAIL_SENDER:test@ios.ase.cit.tum.de}
    footer: ${MAIL_FOOTER:}
    workspace-url: ${MAIL_WORKSPACE_URL:https://slack.com}
    chair-member-recipients: ${MAIL_CHAIR_RECIPIENTS:}
  storage:
    upload-location: ${UPLOAD_FOLDER:uploads}

server:
  servlet:
    context-path: /api
