logging:
  level:
    liquibase: INFO

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/thesis-track}
    username: ${SPRING_DATASOURCE_USERNAME:thesis-track-postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:thesis-track-postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${DEBUG_MODE:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: ${DEBUG_MODE:false}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:thesis-track-app}
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_HOST:http://localhost:8081}/realms/${KEYCLOAK_REALM_NAME:thesis-track}
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_HOST:http://localhost:8081}/realms/${KEYCLOAK_REALM_NAME:thesis-track}/protocol/openid-connect/certs
          issuer-uri: ${KEYCLOAK_HOST:http://localhost:8081}/realms/${KEYCLOAK_REALM_NAME:thesis-track}
  mail:
    host: ${POSTFIX_HOST:localhost}
    port: ${POSTFIX_PORT:25}
    username: ${POSTFIX_USERNAME:}
    password: ${POSTFIX_PASSWORD:}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          starttls:
            enable: true

server:
  servlet:
    context-path: /api

thesis-track:
  keycloak:
    host: ${KEYCLOAK_HOST:http://localhost:8081}
    realm-name: ${KEYCLOAK_REALM_NAME:thesis-track}
    client-id: ${KEYCLOAK_CLIENT_ID:thesis-track-app}
    service-client:
      id: ${KEYCLOAK_SERVICE_CLIENT_ID:service-client}
      secret: ${KEYCLOAK_SERVICE_CLIENT_SECRET:}
      student-group-name: ${KEYCLOAK_SERVICE_ACCOUNT_STUDENT_GROUP_ID:thesis-students}
  calendar:
    enabled: ${CALDAV_ENABLED:false}
    host: ${CALDAV_HOST:}
    username: ${CALDAV_USERNAME:}
    password: ${CALDAV_PASSWORD:}
  client:
    host: ${CLIENT_HOST:http://localhost:3000}
  mail:
    enabled: ${MAIL_ENABLED:false}
    sender: ${MAIL_SENDER:test@ios.ase.cit.tum.de}
    signature: ${MAIL_SIGNATURE:}
    workspace-url: ${MAIL_WORKSPACE_URL:https://slack.com}
    bcc-recipients: ${MAIL_BCC_RECIPIENTS:}
    mail-template-location: ${MAIL_TEMPLATE_FOLDER:server/mail-templates}
  storage:
    upload-location: ${UPLOAD_FOLDER:uploads}
